nav:
    - index.md
    - neuroverkot    # 100
    - tensorit       # 200
    - vastavirta     # 300
    - mallinnus      # 400
    - konvoluutio    # 500
    - siirtovaikutus # 600
    - kieli          # 700
    - aikasarjat     # 800
    - "*"