nav:
    - index.md
    - "1. Neuroverkot": neuroverkot    # 100
    - "2. Tensorit": tensorit       # 200
    - "3. Vastavirta": vastavirta     # 300
    - "4. Mallinnus": mallinnus      # 400
    - "5. Konvoluutio": konvoluutio    # 500
    - "6. Siirtovaikutus": siirtovaikutus # 600
    - "7. Kieli": kieli          # 700
    - "8. Aikasarjat": aikasarjat     # 800
    - "*"